name: Deploy Portfolio to Google App Engine

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set Credential
      uses: 'google-github-actions/auth@v2'
      with:
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        workload_identity_provider: ${{ secrets.PROVIDER }}
        
    - name: 'Set up gcloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'
        
    - name: Build
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: 'google-github-actions/deploy-appengine@v2'


